USE SAKILA;
-- SELECT DE CUSTOMER CON SUS RESPECTIVOS ADDRESS, STREET

SELECT * FROM CUSTOMER;
SELECT * FROM ADDRESS;
-- FIRST_NAME, EMAIL, ADDRESS, DISTRICT
SELECT * FROM CUSTOMER JOIN ADDRESS ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;  -- UNIR O COMBINAR ES JOIN

SELECT FIRST_NAME, EMAIL, ADDRESS, DISTRICT
FROM CUSTOMER JOIN ADDRESS ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

SELECT C.FIRST_NAME, C.EMAIL, A.ADDRESS, A.DISTRICT
FROM CUSTOMER C JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID;

-- 2 JOINS CUSTOMER CON ADDRESS Y CITY EN UN MISMO SELECT
SELECT CU.EMAIL, A.ADDRESS, CI.CITY
FROM CUSTOMER CU 
JOIN ADDRESS A ON C.ADDRESS_ID = A.ADDRESS_ID
JOIN CITY CI ON A.CITY_ID = CI.CITY_ID
JOIN COUNTRY CO ON CI.COUNTRY_ID = CO.COUNTRY_ID;

