-- crear base de datos many to many
DROP SCHEMA IF EXISTS many_to_many;
create schema many_to_many; -- NO PUEDE HABER 2 USUARIOS CREADOS CON LS MISMA ADDRESS
USE many_to_many;

-- crear tabla libro
CREATE TABLE BOOK ( 
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(100), 
AUTHOR VARCHAR(100),
NUM_PAGES INT 
);
-- crear tabla categoria 
CREATE TABLE CATEGORY ( 
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100), 
MIN_AGE INT 
);
CREATE TABLE BOOK_CATEGORY ( 
ID_BOOK INT,
ID_CATEGORY INT,
PRIMARY KEY(ID_BOOK, ID_CATEGORY), -- CLAVE PRIMARIA COMPUESTA
foreign key (ID_BOOK) REFERENCES BOOK(ID),
foreign key (ID_CATEGORY) REFERENCES CATEGORY(ID)
);

INSERT INTO BOOK (TITULO, AUTHOR, NUM_PAG) VALUES
('CIEN AÑOS DE SOLEDAD', 'ggm', '500'),
('libro2', 'luis', '200'),
('libro 3', 'carmen','300');

INSERT INTO CATEGORY (NAME, MIN_AGE ) VALUES
('ACCION','18'),
('COMEDIA','20'),
('ROMANCE','15');

SELECT * FROM BOOK;
SELECT * FROM CATEGORY;
SELECT * FROM BOOK_CATEGORY;
INSERT INTO BOOK_CATEGORY(ID_BOOK, ID_CATEGORY) VALUES
(1, 1), -- ASOCIA ACCION A BOOK1
(1, 2), -- ASOCIA COMEDIA A BOOK1
-- (1,1) -- aSOCIA ACCION A BOOK1 -- NO SE PUEDE PORQUE YA LO ESTA
(3, 1)
;
-- RESULTADO LIBRO 1 TIENE CATEGRIA ACCION Y COMEDIA
-- RESULTADO LIBRO 3 TIENE CATEGRIA ACCION
-- si se vuel a ejecutar el insert tal cual de error porque no se puede duplicar
-- una categia en un mismo libro
-- error code: 1062. duplicate entry