-- crear base de datos one to one
DROP SCHEMA IF EXISTS one_to_one;
create schema one_to_one; -- NO PUEDE HABER 2 USUARIOS CREADOS CON LAS MISMA ADDRESS
USE one_to_one;

-- CREATE TABLE ADDRESS 
CREATE TABLE ADDRESS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
STREET VARCHAR(250) NOT NULL, 
POSTAL_CODE VARCHAR(5),
CITY VARCHAR(50)
);

-- CREATE TABLA USERS
CREATE TABLE `USERS` (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(100),
ID_ADDRESS INT UNIQUE, -- RESTRICCION DE UNICIDAD
FOREIGN KEY (ID_ADDRESS) REFERENCES ADDRESS(ID)
);

INSERT INTO ADDRESS (STREET, POSTAL_CODE, CITY) VALUES
('CALLE ALCALA', '67684', 'MADRID'),
('CALLE ILA', '56825', 'CARACAS'),
('CALLE CARAMELO', '52285','MADRID'),
('CALLE ABUNDANCIA', 56785,'CARACAS');

INSERT INTO USERS (FIRST_NAME, LAST_NAME, EMAIL, ID_ADDRESS) VALUES
('USER 1', 'APELLIDO1', 'MADRID1@GMAIL.COM', 1),
('USER 2', 'APELLIDO2', 'MADRID2@GMAIL.COM', 2);

-- ES COMO MANY TO ONE PERO AÑADIENDO unique en la columna que sera la clave foranea